/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ie.httpeasy.request;

import org.junit.Test;
import static org.junit.Assert.*;

public class HttpRequestTest {
    final String testSuccessURL = "www.google.com";
    final String testFailURL = "www.asksmdksdn.com";
    @Test public void testConnection() {
        HttpRequest classUnderTest = new HttpRequest(testSuccessURL);
        assertTrue("Connection to " + testSuccessURL + " should work!", classUnderTest.isConnectionSuccessful());
        assertFalse("Connection to " + testSuccessURL + " should work!", classUnderTest.isConnectionFailed());
        classUnderTest = new HttpRequest(testFailURL);
        assertFalse("Connection to " + testFailURL + " should not work!", classUnderTest.isConnectionSuccessful());
        assertTrue("Connection to " + testFailURL + " should not work!", classUnderTest.isConnectionFailed());
    }
}
