/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ie.httpeasy.request;

import java.io.IOException;
import java.net.*;

public class HttpRequest {
    private Socket client;
    private int port;

    public HttpRequest(String serverName) {
        this(serverName, 80);
    }
    public HttpRequest(String serverName, int port) {
        System.out.printf("Connecting to '%s' on port %s\n", serverName, port);
        try {
            client = new Socket(serverName, port);
            this.port = port;
        } catch (IOException e) {
            client = null;
            this.port = -1;
            System.out.println("Connection failed!");
        }
    }

    public boolean isConnectionSuccessful() {
        return (client != null) && (port > 0);
    }

    public boolean isConnectionFailed() {
        return !isConnectionSuccessful();
    }
}
