/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ie.httpeasy.response;

import ie.httpeasy.response.HttpResponse;

import org.junit.Test;
import static org.junit.Assert.*;

public class HttpResponseTest {
    @Test public void testSomeLibraryMethod() {
        HttpResponse classUnderTest = new HttpResponse();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
